[tool.black]
line-length = 119
skip-string-normalization = false
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''

[tool.isort]
line_length = 119
multi_line_output = 3
include_trailing_comma = true
known_first_party = 'apps'
skip_glob = ["*/migrations/*"]

[tool.coverage.run]
omit = [
  '*/migrations/*',
  '*/tests/*',
  'property_management/asgi.py',
  'property_management/wsgi.py',
  'property_management/settings.py',
  'conftest.py',
  'docs/*',
  'manage.py',
]

[tool.coverage.html]
show_contexts = true

[tool.mypy]
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]

[[tool.mypy.overrides]]
module = "*.migrations.*"
ignore_errors = true

[tool.django-stubs]
django_settings_module = "property_management.settings"
ignore_missing_model_attributes = true
