# Generated by Django 4.1.4 on 2024-02-10 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
        ("authentication", "0002_user_company_name_user_mobile_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="subscription",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_subscription",
                to="subscription.subscription",
                verbose_name="subscription",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="associated_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="subscription.subscription",
            ),
        ),
    ]
