# Generated by Django 4.1.4 on 2024-02-10 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
        ("system_preferences", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessinformation",
            name="subscription",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_subscription",
                to="subscription.subscription",
                verbose_name="subscription",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactcategory",
            name="subscription",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_subscription",
                to="subscription.subscription",
                verbose_name="subscription",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventoryitemtype",
            name="subscription",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_subscription",
                to="subscription.subscription",
                verbose_name="subscription",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventorylocation",
            name="subscription",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_subscription",
                to="subscription.subscription",
                verbose_name="subscription",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="label",
            name="subscription",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_subscription",
                to="subscription.subscription",
                verbose_name="subscription",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="managementfee",
            name="subscription",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_subscription",
                to="subscription.subscription",
                verbose_name="subscription",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="propertytype",
            name="subscription",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_subscription",
                to="subscription.subscription",
                verbose_name="subscription",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="subscription",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_subscription",
                to="subscription.subscription",
                verbose_name="subscription",
            ),
            preserve_default=False,
        ),
    ]
